language: ruby
rvm:
  - "2.0.0"
services: mongodb
script: bundle exec rake test
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change

notifications:
  slack: mitre-crucible:A1c8nXacZlK4NVoOcPFTI6Sc

travis encrypt "mitre-crucible:A1c8nXacZlK4NVoOcPFTI6Sc" --add notifications.slack
